apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: fatura-personalizada-v2
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - api.fatura-personalizada.oondemand.com.br
    - ai.fatura-personalizada.oondemand.com.br
    - fatura-personalizada.oondemand.com.br