apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: doc-custom-homolog
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - homolog.doc-custom.oondemand.com.br
    - homolog.api.doc-custom.oondemand.com.br
