apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: rakuten
spec:
  secretName: app-tls
  issuerRef:
    name: letsencrypt-nginx
    kind: ClusterIssuer
  dnsNames:
    - cst.rakuten.segeti.oondemand.com.br
    - api.rakuten.segeti.oondemand.com.br
    - app.rakuten.segeti.oondemand.com.br